config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/") 

  root "contacts#index"

  get 'home/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /contacts or /contacts.json
  def index
    if user_signed_in?
      @contacts = Contact.where(user_id: current_user.id)
    end

    []
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = current_user.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not authorized to edit this contact" if @contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :contact_number, :physical_address, :billing_address, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<div class="card py-5 px-4">
  <p class="display-4"><%= contact.name %></p>
  <p class="lead"><%= contact.contact_number %></p>
  <hr class="hr">
  <address>
    <strong>Physical address:</strong>
    <%= contact.physical_address %>
  </address>
  <address>
    <strong>Billing address:</strong>
    <%= contact.billing_address %>
  </address>
  <div>
    <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
    <%= link_to "Back to contacts", contacts_path %>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="mb-3">
        <% form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>

    <div class="mb-3">
        <% form.label :contact_number, class: "form-label" %>
        <%= form.text_field :contact_number, class: "form-control", placeholder: "Contact Number" %>
    </div>

    <div class="mb-3 form-label">
        <% form.label :physical_address, class: "form-label" %>
        <%= form.text_field :physical_address, class: "form-control", placeholder: "Physical Address" %>
    </div>

    <div class="mb-3 form-label">
        <% form.label :billing_address, class: "form-label" %>
        <%= form.text_field :billing_address, class: "form-control", placeholder: "Billing Address" %>
    </div>

    <div class="mb-3 form-label">
        <% form.label :user_id,id: :contact_user_id, class: "form-label" %>
        <%= form.number_field :user_id, class: "form-control", value: current_user.id, type: :hidden %>
    </div>

    <%= form.submit class: "btn btn-dark" %>
  </form>
<% end %>

app/views/contacts/edit.html.erb
<h1 class="display-4 mb-4">Edit Contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<% if user_signed_in? %>
  <h2 class="mb-3">Hello! <%= current_user.email if current_user %></h2>
  <%= link_to "New contact", new_contact_path, class: "btn btn-dark" %>
  <table class="table mt-3">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Contact Number</th>
        <th scope="col">Physical Address</th>
        <th scope="col">Billing Address</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= link_to contact.name, contact %></td>
          <td><%= contact.contact_number %></td>
          <td><%= contact.physical_address %></td>
          <td><%= contact.billing_address %></td>
          <td><%= button_to "Delete", contact, method: :delete, class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
<% end %>

app/views/contacts/new.html.erb
<h1 class="display-4 mb-4">Create Contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<%= render @contact %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container">
    <%= link_to "CMS", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Contacts", contacts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CmsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/navigation" %>



    <div class="container pt-4"> 
      <% if notice %>
        <%= render "layouts/alerts" %>
       <% end %>
      <%= yield %>
    </div>
  </body>
</html>